default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-xml
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: /README\.rst$
      - id: trailing-whitespace
        exclude: /README\.rst$
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/OCA/pylint-odoo
    rev: v9.3.15
    hooks:
      - id: pylint_odoo
        args: ["--rcfile=.pylintrc"]
  - repo: https://github.com/oca/maintainer-tools
    rev: c08659518fb287683074f0a6aacda984815ac7b1
    hooks:
      - id: oca-gen-addon-readme
        args:
          - --addons-dir=addons
          - --branch=19.0
          - --org-name=YOUR-GITHUB-USER
          - --repo-name=odoolings-starter
          - --if-source-changed
